### ISSUE TITLE
Requires tornado<4.0.0?

### ISSUE THREAD

**Issue by sssilver** [globocom/tornado-cors#10]
Any particular reason for the version requirement?

**Comment by gcirne** [comment]
Hmm, I don't really remember. It was probably just a safeguard.

Would you like to test it with tornado 4?

**Comment by felipead** [comment]
Hi. Thank you for this awesome library.

I'm not sure the library already works with Tornado 4.1 (I see an issue for that was closed).

However, the requirements.txt still specify tornado<4.0.0. So this makes it impossible to install tornado-cors with tornado 4.1 through pip.

Let me know how I can help. I would love to contribute.

Thanks!

**Comment by gcirne** [comment]
Issue #13 was closed because it was deemed to be a duplicate of this one.

If you have the time, you could help by testing this with tornado 4.1. If it works, send a PR with an updated requirements.txt.

Thanks!

**Comment by felipead** [comment]
Version 0.6.0 released today adds Tornado 4.1 support. You can close this issue.

**Comment by sssilver** [comment]
Cool, thanks!
